"""add public portfolio fields

Revision ID: a7c2d99f565f
Revises: 142d22447061
Create Date: 2026-07-26 12:04:27.696595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c2d99f565f'
down_revision: Union[str, Sequence[str], None] = '142d22447061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "users",
    sa.Column(
        "is_public",
        sa.Boolean(),
        nullable=False,
        server_default=sa.true(),
    ),
    )
    op.alter_column(
        "users",
        "is_public",
        server_default=None,
    )
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_public')
    # ### end Alembic commands ###
